Allow multiple possible library paths
ibmruntimes/openj9-openjdk-jdk12 pull request #58
Opened 2019-06-18 16:15 UTC by adamfarley

Currently, if the cumulative total length of all possible library
paths is greater than the maximum length of a single path (on this
OS), then the path to the library is left blank. This results in
failure to load the library.

This fix is the all-platforms port for the PR linked below, and
enables each separate path to be measured for length independent of
its neighbours.

https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/107

Signed-off-by: Adam Farley <adam.farley@uk.ibm.com>

2019-06-19 12:57 UTC, lumpfish approved these changes

2019-06-19 16:35 UTC, keithc-ca approved these changes

2019-06-19 16:35 UTC, keithc-ca commented
Jenkins compile zlinux jdk12

2019-06-19 17:21 UTC, keithc-ca commented
Please fix the compile error; see https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/121#discussion_r295407208.

2019-06-20 12:03 UTC, keithc-ca commented
@AdamBrousseau Any theories why we see `Pull Request - OpenJDK12` and `Pull Request - OpenJDK10` above which both link to the same jdk12 job?

2019-06-20 12:27 UTC, AdamBrousseau commented
When I created the 13 job, copied from the 12 job, I noticed it said 10 when I was updating it to 13. So I then proceeded to update the 12 build as well. Likely while your build was running.

2019-06-20 13:16 UTC, adamfarley commented
Re-running checks, as the size_t-int change has been applied to all versions of the jdk for consistency.

2019-06-20 13:19 UTC, adamfarley commented
Jenkins compile win64 jdk12

2019-06-20 13:19 UTC, adamfarley commented
Jenkins compile win jdk12

2019-06-20 13:20 UTC, adamfarley commented
Jenkins compile xlinux jdk12

2019-06-20 14:20 UTC, keithc-ca requested changes
This should change in the same ways as requested for jdk8.

2019-06-21 20:36 UTC, keithc-ca approved these changes

2019-06-21 20:37 UTC, keithc-ca commented
The changes have been vetted in jdk8 and jdk11.

2019-06-21 20:37 UTC, merged