Use Cleaner to free digest native context
ibmruntimes/openj9-openjdk-jdk12 pull request #69
Opened 2019-08-15 17:10 UTC by ashbm5

Signed-off-by: Alon Shalev Housfater <alonsh@ca.ibm.com>

2019-08-15 17:12 UTC, ashbm5 commented
FYI @keithc-ca

2019-08-18 22:09 UTC, keithc-ca requested changes

2019-08-18 22:09 UTC, keithc-ca commented on closed/src/java.base/share/classes/sun/security/provider/NativeDigest.java
> +        private long digestCtx;
Please apply the same fixes as were made for jdk8. Here, make the class and field `final`.

2019-08-18 22:09 UTC, keithc-ca commented on closed/src/java.base/share/classes/sun/security/provider/NativeDigest.java
> +        digestCleaner.register(this, new DigestCleanerRunnable(this.context));
The call to `register` should move after the validation check (also in `clone()`).

2019-08-18 22:09 UTC, keithc-ca commented on src/java.base/share/classes/sun/security/provider/SunEntries.java
>       * The property 'jdk.nativeCrypto' is used to disable all native cryptos (Digest,
Please fix the comment: restore from commit 9ac2440.

2019-08-19 16:29 UTC, ashbm5 commented
@keithc-ca updated

2019-08-19 17:05 UTC, keithc-ca requested changes

2019-08-19 17:05 UTC, keithc-ca commented on src/java.base/share/classes/sun/security/provider/SunEntries.java
> +     * and 'jdk.nativeCrypto' is used to disable all native cryptos (Digest,
Please remove trailing whitespace from this line.

2019-08-19 17:59 UTC, ashbm5 commented
updated

2019-08-20 17:52 UTC, keithc-ca commented
Jenkins test extended plinux jdk12

2019-08-20 21:04 UTC, keithc-ca approved these changes

2019-08-20 21:04 UTC, merged